name: Build EXE

on:
  push:
    paths: [DateNotifier.py, requirements.txt]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed DateNotifier.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DateNotifier_exe
        path: dist/DateNotifier.exe
